# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Cache python modules
      uses: actions/cache@v1
      env:
        cache-name: cache-python-modules
      with:
        path: ~/.cache/pipenv
        key: ${{ runner.os }}-build-python-${{ env.cache-name }}-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-python-${{ env.cache-name }}-
          ${{ runner.os }}-build-python-
          ${{ runner.os }}-

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: test django
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pipenv
        pipenv install
        pipenv run ./backend/manage.py makemigrations --dry-run --check --noinput

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-npm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-npm-${{ env.cache-name }}-
          ${{ runner.os }}-build-npm-
          ${{ runner.os }}-

    - name: test frontend build
      run: |
        npm install
        npm run build
      working-directory: ./frontend

    - if: github.event_name == 'push'
      name: Deploy to Server
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
      with:
        source: "./frontend/build,./backend,Pipfile,production.txt"
        target: "~"

    - if: github.event_name == 'push'
      name: execute remote deploy.sh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: sh deploy.sh
